import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DotGrid from "@/components/DotGrid";
import GridBgLayout from "@/components/layouts/grid-bg-layout";
import { Header } from "@/components/layouts/header";
import PageContainer from "@/components/layouts/page-container";
import TargetCursor from "@/components/TargetCursor";
import { FloatingDock } from "@/components/ui/floating-dock";
import { FloatingDockWrapper } from "@/components/layouts/floating-dock-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[1000px]`}
      >
        <TargetCursor spinDuration={2} />

        <GridBgLayout>
          <PageContainer>
            <Header />
            {children}
            <FloatingDockWrapper />
          </PageContainer>
        </GridBgLayout>
      </body>
    </html>
  );
}
